site_name: Python Project Template

repo_url: https://github.com/bdura/project-template

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - content.code.annotate

nav:
  - index.md
  - reading-list.md
  - How-to:
      - howto/index.md
      - howto/dependency-management.md
  - Environment:
      - environment/index.md
      - IDE: environment/ide.md
      - environment/git.md
      - environment/zsh.md
  - Python:
      - python/index.md
      - python/awesome.md
      - python/documentation.md
      - python/configuration.md
      - python/reproducibility.md
  - Code Reference: reference/
  - changelog.md
  - roadmap.md

extra_css:
  - assets/stylesheets/extra.css
  - assets/termynal/termynal.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - assets/termynal/termynal.js

watch:
  - roadmap.md
  - changelog.md

extra:
  version:
    provider: mike

plugins:
  - search
  - bibtex:
      bib_file: "docs/references.bib"
  - gen-files:
      scripts:
        - docs/scripts/reference.py
        - docs/scripts/development.py
  - literate-nav:
      nav_file: SUMMARY.md
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            heading_level: 2
            members_order: source
            show_root_toc_entry: false
  - glightbox:
      touchNavigation: true
      loop: false
      effect: none
      width: 100%
      height: auto
      zoomable: true
      draggable: true
  - mike

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
