name: Documentation

on:
  push:
    branches: [main]

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Set PY variable
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.3.2
          poetry config cache-dir ~/.cache/poetry

      - uses: actions/cache@v2
        with:
          path: ~/.cache/poetry
          key: poetry|${{ env.PY }}|${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        run: poetry install --with docs

      - name: Set up Git
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"

      - name: Build documentation
        run: |
          git fetch origin gh-pages
          poetry run mike delete master
          poetry run mike deploy --push master
